version: '2'
volumes:
  # Postgres Data
  marshall-postgres-data:
    driver: local
    
services:    
  db1:
    image: postgres:10.3
  
    volumes:
      - marshall-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      DB_HOST: db1
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: knowledge_stats

  web:
    image: ambientum/node:9
  
    command: npm run start
    volumes:
      - .:/usr/src/app/
      - marshall-postgres-data:/var/lib/postgresql/data
      - ./sessions:/usr/src/app/sessions
      #- /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db1
      - mongo
    environment:
      DB_HOST: db1
    links:
      - db1
  